projectTitle = "Block Beams"
modId = "block_beams"
modVersion = "1.2.1"
group = "com.theendercore"
githubRepo = "theendercore/BlockBeams"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "TheEnderCore" ]
majorMinecraftVersion = "1.21.4"
minecraftVersion = "1.21.4"
fabricLoaderVersion = "0.16.13"
fabricApiVersion = "0.119.2+1.21.4"
fabricLangKotlinVersion = "1.13.2+kotlin.2.1.20"
license = "MIT"
modules = [ ]
modDescription = "A very simple mod that spawns a beam of colored particles above a block."
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ ]
disableKotlin = false

[mappings]
    # You have 7 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    # CUSTOM: Custom mapping jar. Uses mappings version as file location
    type = "MOJANG"
    version = "1.21.4"