[versions]
kotlin = "2.2.20"
fabric-loom = "1.11-SNAPSHOT"
iridium = "3.5.0"

modmenu = "15.0.0"

[libraries]
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
iridium = { id = "org.teamvoided.iridium", version.ref = "iridium"}
iridium-publish = { id = "iridium.project.publish-script", version.ref = "iridium"}
iridium-upload = { id = "iridium.mod.upload-script", version.ref = "iridium" }